### ISSUE TITLE
Add self-contained version

### ISSUE THREAD

**Issue by MihaMarkic** [onovotny/SignService#13] opened 2017-04-28 14:00 UTC
Can you add a self-contained version of SignClient (including nuget package) so ti can be easily used with [Cake](http://cakebuild.net/)?

**Comment by onovotny** [comment] 2017-04-28 14:37
The problem is that makes the nuget package >30 megs...

**Comment by MihaMarkic** [comment] 2017-04-28 14:47
Not a problem I guess, as it is optional and used by those who need it?

**Comment by MihaMarkic** [comment] 2017-04-28 14:57
I mean you'd have two NuGet packages...

**Comment by gep13** [comment] 2017-04-28 21:13
@onovotny I would agree with @MihaMarkic here, I would see them as two separate NuGet's.  Is this something that you would think about doing?  Thanks!

**Comment by onovotny** [comment] 2017-04-29 02:11
I'm still not sure what the key issue is here? why does it need to be a standalone package?

**Comment by MihaMarkic** [comment] 2017-04-29 10:29
OTOH why would anybody have to install .net core system wide just to run a command line tool? The size isn't that important vs no trouble installation IMO and it be even better once native compiler will be available.
With a standalone option the user (of a Cake script) will have to place a single NuGet instruction in script. With a dependent version it won't be that easy.

**Comment by onovotny** [comment] 2017-04-29 19:41
The whole point of .NET Core is to be portable, which this is. If I have to publish a standalone app, then I have to choose which runtimes to publish, and maintain that. The package size becomes *n* x runtime, which is silly.

I would suggest that a better option is to have a way to specify .NET Core as a Cake dependency. Let Cake resolve that this tool requires .NET Core. If it's not already installed, it'll download/install a local copy of .NET Core that's specific to the runtime Cake is executing on. To me, that makes far more sense than each individual tool providing 5+ runtimes.

**Comment by gep13** [comment] 2017-04-29 20:16
@onovotny so that is effectively what we are doing right now within the main Cake build script.

We are restoring .NET Core within the bootstrapper (as it isn't a simple NuGet package installation) as you can see here:

https://github.com/cake-build/cake/blob/develop/build.ps1#L48

And from there, we are invoking the SignClient:

https://github.com/cake-build/cake/blob/develop/build.cake#L385

What @MihaMarkic is requesting is an ability to streamline that process, by only having to do:

```
#tool "nuget:?package=SignClient.<Runtime>"
```

Rather than having to do the additional work.  I can see where that request is coming from, but I also take your point but supporting the various runtimes.

If users are already using Cake.CoreCLR, then they can assume that .NET Core is already going to be present, but those using Cake.exe can't make that assumption.

**Comment by onovotny** [comment] 2017-04-30 00:38
Would you two be available sometime this coming week to have a quick call to discuss this further? 9-5 pm eastern time in NY would be ideal if we can fit something in, otherwise, bet 8-10pm could work too.

My concern is that having each add-in bundle every runtime seems counter to the way things are working today. Take another example of xUnit -- it now has a CoreCLR runner that you can use. Should it also package every version of every runtime locally within its package? Overall, I don't think that architecture scales well...

What could work is a more generalized mechanism based on what you already have to install .NET Core but as an overall dependency. 

The build script (or the add-in) would specify that it does need .NET Core and Cake would ensure that the required .NET Core runtime version (now 1.1, but soon 2.x) is available. If not already present globally on the machine, it can invoke the scripts to provide a local version.

Then every subsequent add-in that needs to use `dotnet` can safely assume it's available by virtue of having declared the dependency. Would that work? Happy to discuss further if you'd like.

**Comment by onovotny** [comment] 2017-12-18 23:15
I'm going to close this in favor of https://github.com/onovotny/SignService/issues/23, once Global Commands are available. 

I'd still love to see a nice Cake wrapper/addin/whatever that makes it easier to invoke the client.

**Closed by onovotny** 2017-12-18 23:15 UTC

**Comment by gep13** [comment] 2018-01-09 07:19
>@onovotny said...
I'd still love to see a nice Cake wrapper/addin/whatever that makes it easier to invoke the client.

The Cake Wrapper is all but finished:

https://github.com/cake-contrib/Cake.SignClient

However, we just need to make it invoke dotnet first, rather than shelling out to an exe.  It has been on my list for a while to finalise this, but just haven't had the time.

**Comment by onovotny** [comment] 2018-01-09 12:58
@gep13 thanks, not sure how I missed that

**Comment by gep13** [comment] 2018-01-09 14:06
>@onovotny said..
thanks, not sure how I missed that

If you wanted to send a PR through, you would be more than welcome `</nerdsnipe>`
